<cnn> ::= <c_layer> <h_layer> <d_layer>


<c_layer> ::= <conv>

<h_layer> ::= <h_node> <h_layer> | '&'

<d_layer> ::= <d_node> <dense>


<h_node> ::= <conv> <h_node> | '&'

<d_node> ::= <dense> <d_node> | '&'


<conv> ::= 'Conv' <filters> <k_size>

<dense> ::= 'Dense' <units>


<filters> ::= '32' | '64'

<k_size> ::= '(3, 3)' | '(5, 5)'

<units> ::= '32' | '64'