<cnn> ::= <conv> <c_layer> <d_layer> <dense>


<c_layer> ::= <c_layer> <c_layer> | <c_node> | '&'

<d_layer> ::= <d_node> <d_node> | <d_node> | '&'


<c_node> ::= <conv>

<d_node> ::= <dense>


<conv> ::= 'class_name' 'Conv2D' 'filters' <filters> 'kernel_size' <k_size>

<dense> ::= 'class_name' 'Dense' 'units' <units>


<filters> ::= '32' | '64'

<k_size> ::= '(3, 3)' | '(5, 5)'

<units> ::= '32' | '64'