<cnn> ::= <conv> <c_layer> <d_layer> <dense>

<c_layer> ::= <c_layer> <c_layer> | <c_node> | &

<d_layer> ::= <d_node> <d_node> | <d_node> | &


<c_node> ::= <conv> | <pool>

<d_node> ::= <dense> | <dropout>


<conv> ::= conv <filters> <ksize> <strides> <padding> <activation>

<dense> ::= dense <units>

<dropout> ::= dropout <rate>

<pool> ::= <pool_type> <psize> <padding>


<pool_type> ::= maxpool | avgpool

<activation> ::= relu | selu | elu | tanh | sigmoid | linear

<padding> ::= valid | same

<filters> ::= 16 | 32 | 64 | 128

<strides> ::= 1 | 2

<ksize> ::= 3 | 5 | 7

<psize> ::= 2 | 4 | 6

<units> ::= 32 | 64 | 128 | 256

<rate> ::= [0.0,0.5]