<RE>            ::= <elementary-RE><RE>|<elementary-RE>

<elementary-RE> ::= [<RE>]|(<RE>)|<set>|<range>|<modifier>|<char>|\w|\d|{<match_times>}|<lookarounds>

<modifier>      ::= ^<RE>|<RE>.|<RE>*|<RE>+|<RE>++|<RE>?|<RE>?+|<RE>"|"<RE>

<lookarounds>   ::= (?"<"=<RE>)|(?"<"!<RE>)|(?=<RE>)|(?!<RE>)|(?:<RE>)|<RE>{<RE>,<RE>}+

<set>           ::= <char>|<char><set>

<range>         ::= <an_char>-<an_char>|<an_char>-<an_char>|A-Z|a-z|0-9

<char>          ::= <s_char>|<an_char>|<an_char>|<an_char>
<an_char>       ::= <0_9>|<A_Z>|<a_z>

<match_times>   ::= <recur_digit>|<recur_digit>,|<recur_digit>,<recur_digit>
<recur_digit>   ::= <0_9>|<0_9><recur_digit>

<A_Z>           ::= A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z
<a_z>           ::= a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z
<0_9>           ::= 0|1|2|3|4|5|6|7|8|9
<s_char>        ::= !|"#"|$|%|&|\(|\)|*|+|,|-|.|\/|:|;|"<"|=|">"|?|@|\[|\\|\]|^|_|"`"|{|}|~|"|"|'\"'|"'"|" "
