<unet> ::= <conv> <next>

<next> ::= <conv> <next> | <pool> <nextp> | bridge <pool> <nextp> | <midle>
<nextp> ::= <conv> <next> | <midle>
<midle> ::= <midle> <midle> | <conv> | <dropout>

<conv> ::= conv 32 3 1 same relu
<pool> ::= maxpool 2 2 same
<upsamp> ::= upsamp 2
<dropout> ::= dropout 0.5


<filters> ::= 2 | 4 | 8 | 16 | 32 | 64 | 128 | 256 | 512 | 1024
<kernel_size> ::= 1 | 2 | 3 | 4 | 5 | 6 | 7
<strides> ::= 1 | 2
<padding> ::= valid | same
<activation> ::= relu | sigmoid | linear
<rate> ::= [0.0,0.5]