<unet> ::= <conv> <pair_node> <output>


<pair_node> ::= <conv> <pair_node> <conv> | <pool> <pair_node_p> <upsamp> <concat>
<pair_node_p> ::= <conv> <pair_node> <conv> | <midle>
<midle> ::= <conv> | <dropout> | <midle> <midle>
<output> ::= conv 2 1 <strides> <padding> sigmoid


<conv> ::= conv <filters> <kernel_size> <strides> <padding> <activation>
<pool> ::= maxpool <kernel_size> <strides> <padding>
<upsamp> ::= upsamp <kernel_size>
<dropout> ::= dropout <rate>
<concat> ::= concat 3


<filters> ::= 2 | 4 | 8 | 16 | 32 | 64 | 128 | 256 | 512 | 1024
<kernel_size> ::= 1 | 2 | 3
<strides> ::= 1 | 2
<padding> ::= valid | same
<activation> ::= relu | sigmoid | linear
<rate> ::= [0.0,0.5]