<unet> ::= <conv> <pair_node> <output>


<pair_node> ::= <conv> <pair_node> <conv> | <dropout> <pair_node_p> <upsamp> <concat>

<pair_node_p> ::= <conv> <pair_node> <conv> | <midle>

<midle> ::= <conv> 

<output> ::= <conv>


<conv> ::= conv 32 3 1 valid relu

<upsamp> ::= upsamp 2

<dropout> ::= dropout 0.5

<concat> ::= concat 3